# Generated by Django 3.2.10 on 2025-01-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
    ]
