# Generated by Django 3.2.10 on 2025-01-27 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_sharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_sharing', '0003_auto_20250124_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encrypted_key',
            field=models.CharField(default=file_sharing.models.generate_key, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
